[project]
name = "videoera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "hydra-core>=1.3.2",
    "lightning>=2.5.5",
    "omegaconf>=2.3.0",
    "opencv-python>=4.12.0.88",
    "torchvision>=0.23.0",
]
